In [13]:
import pickle

# Path to your pickle file
file_path = 'data/simulated_data.pkl'

# Load the pickle file
with open(file_path, 'rb') as file:
    data = pickle.load(file)

C:\Users\Gili\AppData\Local\Temp\ipykernel_31212\347073154.py:8: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  data = pickle.load(file)

In [14]:
data

,subject,block,trial,first_trial_in_block,choice1,choice2,choice3,state1,state2,state3,expval_ch,reward,0,1,2,3,4,5,6,7
0,1,1,1,1,1,1,1,1,1,1,0.676316,1,0.676316,0.503852,0.461245,0.420982,0.581164,0.335714,0.504083,0.203272
1,1,1,2,0,1,1,1,1,1,1,0.718574,0,0.718574,0.529108,0.516754,0.414492,0.604535,0.304579,0.496339,0.200000
2,1,1,3,0,1,1,1,1,1,1,0.730736,1,0.730736,0.574679,0.497429,0.368280,0.630029,0.300220,0.468945,0.222742
3,1,1,4,0,1,1,1,1,1,1,0.791362,1,0.791362,0.621871,0.487334,0.394519,0.641600,0.294959,0.492881,0.237957
4,1,1,5,0,2,2,2,1,2,4,0.241371,0,0.797462,0.631489,0.471919,0.368573,0.640499,0.297796,0.491252,0.241371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,2,96,0,2,1,2,1,2,3,0.717943,1,0.644003,0.420958,0.455643,0.393157,0.596880,0.717943,0.286208,0.414320
196,1,2,97,0,1,1,1,1,1,1,0.670891,1,0.670891,0.409716,0.451754,0.372557,0.591295,0.738498,0.305613,0.432670
197,1,2,98,0,1,1,1,1,1,1,0.693161,1,0.693161,0.407086,0.447461,0.366618,0.609831,0.721749,0.284086,0.425419
198,1,2,99,0,2,1,2,1,2,3,0.735800,1,0.659840,0.446370,0.468859,0.337650,0.586229,0.735800,0.299215,0.435218
199,1,2,100,0,2,1,1,1,2,3,0.585462,1,0.664805,0.444032,0.489354,0.343661,0.585462,0.686015,0.300521,0.429595